/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "minifyjpeg.h"

int *
add_1_svc(number *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	
	
	printf ("gotta add numbers...\n");
	
	struct numbers{
			int num1;
			int num2;
	}*argstruct;
	
	argstruct = rqstp;
	
	
	printf("Numbers to add are: %d, %d. Adding...\n", argstruct->num1, argstruct->num2);
	printf ("the result is %d\n", argstruct->num1 + argstruct->num2);
	
	result = argstruct->num1+argstruct->num2;
	
	
	

	return &result;
}
